import { BidPackage, ActivityLog } from './types';

export const INITIAL_BID_PACKAGES: BidPackage[] = [
  {
    id: 'GT-01/XL-2026',
    name: 'Thi công xây lắp khối nhà chính và hạ tầng kỹ thuật',
    type: 'Xây lắp',
    selectionMethod: 'Đấu thầu rộng rãi',
    budget: 152000000000,
    contractValue: 148500000000,
    contractor: 'Tổng công ty Xây dựng Trường Sơn',
    progress: 75,
    status: 'Hoàn thành',
    startDate: '2026-01-15',
    endDate: '2026-12-30',
    manager: 'Nguyễn Văn Hùng',
    department: 'Ban Quản lý Dự án số 1',
    disbursement: 110000000000,
    notes: 'Tiến độ xây lắp đảm bảo kế hoạch đề ra. Đang thi công sàn tầng 8.',
    approvalDate: '2026-01-05',
    contractDate: '2026-01-10',
  },
  {
    id: 'GT-02/TB-2026',
    name: 'Cung cấp và lắp đặt hệ thống cơ điện (MEP) toàn khu',
    type: 'Thiết bị',
    selectionMethod: 'Đấu thầu rộng rãi',
    budget: 85000000000,
    contractValue: 83200000000,
    contractor: 'Công ty Cổ phần REE M&E',
    progress: 40,
    status: 'Hoàn thành',
    startDate: '2026-03-01',
    endDate: '2026-11-15',
    manager: 'Trần Hoài Nam',
    department: 'Ban Quản lý Dự án số 1',
    disbursement: 35000000000,
    notes: 'Đang nhập khẩu thiết bị Chiller. Lắp đặt hệ thống ống gió đạt 60%.',
    approvalDate: '2026-02-15',
    contractDate: '2026-02-28',
  },
  {
    id: 'GT-03/TV-2026',
    name: 'Tư vấn giám sát thi công xây dựng và lắp đặt thiết bị',
    type: 'Tư vấn',
    selectionMethod: 'Chỉ định thầu',
    budget: 4500000000,
    contractValue: 4350000000,
    contractor: 'Công ty Cổ phần Tư vấn CONINCO',
    progress: 65,
    status: 'Hoàn thành',
    startDate: '2026-01-10',
    endDate: '2027-01-15',
    manager: 'Lê Hoàng Minh',
    department: 'Phòng Quản lý Kỹ thuật',
    disbursement: 2800000000,
    notes: 'Giám sát thường trực tại hiện trường, báo cáo chất lượng hàng ngày.',
    approvalDate: '2026-01-05',
    contractDate: '2026-01-08',
  },
  {
    id: 'GT-04/XL-2026',
    name: 'Thi công hệ thống đường nội bộ, thoát nước và cảnh quan',
    type: 'Xây lắp',
    selectionMethod: 'Chào hàng cạnh tranh',
    budget: 24000000000,
    contractValue: 22800000000,
    contractor: 'Công ty TNHH Đầu tư Xây dựng Minh Đăng',
    progress: 20,
    status: 'Hoàn thành',
    startDate: '2026-04-10',
    endDate: '2026-09-30',
    manager: 'Phạm Đức Duy',
    department: 'Ban Quản lý Dự án số 2',
    disbursement: 5000000000,
    notes: 'Chậm 15 ngày so với tiến độ do vướng mặt bằng thi công cống thoát nước chính.',
    approvalDate: '2026-04-01',
    contractDate: '2026-04-08',
  },
  {
    id: 'GT-05/TB-2026',
    name: 'Cung cấp và lắp đặt hệ thống thang máy tốc độ cao (8 chiếc)',
    type: 'Thiết bị',
    selectionMethod: 'Đấu thầu rộng rãi',
    budget: 31000000000,
    contractValue: 30500000000,
    contractor: 'Công ty TNHH Thang máy Otis Việt Nam',
    progress: 95,
    status: 'Hoàn thành',
    startDate: '2026-02-15',
    endDate: '2026-06-20',
    manager: 'Vũ Minh Tuấn',
    department: 'Phòng Thiết bị Công nghệ',
    disbursement: 29000000000,
    notes: 'Đã nghiệm thu kỹ thuật và vận hành thử nghiệm đạt yêu cầu. Đang làm thủ tục bàn giao.',
    approvalDate: '2026-02-10',
    contractDate: '2026-02-12',
  },
  {
    id: 'GT-06/XL-2026',
    name: 'Thi công trạm biến áp 110kV và đường dây đấu nối trung thế',
    type: 'Xây lắp',
    selectionMethod: 'Đấu thầu rộng rãi',
    budget: 42000000000,
    contractValue: 40800000000,
    contractor: 'Tổng công ty Cổ phần Xây dựng Điện Việt Nam (VNECO)',
    progress: 55,
    status: 'Hoàn thành',
    startDate: '2026-02-20',
    endDate: '2026-10-31',
    manager: 'Nguyễn Tiến Dũng',
    department: 'Ban Quản lý Dự án số 2',
    disbursement: 22000000000,
    notes: 'Đã hoàn thành móng trạm biến áp, đang thi công lắp dựng cột thép đấu nối.',
    approvalDate: '2026-02-15',
    contractDate: '2026-02-18',
  },
  {
    id: 'GT-07/TB-2026',
    name: 'Cung cấp hệ thống máy chủ và trang thiết bị CNTT trung tâm dữ liệu',
    type: 'Thiết bị',
    selectionMethod: 'Đấu thầu rộng rãi',
    budget: 18500000000,
    progress: 0,
    status: 'Chậm tiến độ',
    startDate: '2026-07-15',
    endDate: '2026-12-15',
    manager: 'Đỗ Anh Tuấn',
    department: 'Phòng Công nghệ thông tin',
    disbursement: 0,
    notes: 'Đang mở thầu, có 4 nhà thầu nộp hồ sơ hợp lệ. Dự kiến có kết quả trong tháng 8.',
    actualStatus: 'Đang chuẩn bị hồ sơ mời thầu chi tiết.',
    lcntDuration: 45,
  },
  {
    id: 'GT-08/TV-2026',
    name: 'Tư vấn kiểm định chất lượng và đo đạc lún công trình',
    type: 'Tư vấn',
    selectionMethod: 'Chỉ định thầu',
    budget: 1200000000,
    contractValue: 1150000000,
    contractor: 'Viện Khoa học Công nghệ Xây dựng (IBST)',
    progress: 50,
    status: 'Hoàn thành',
    startDate: '2026-01-20',
    endDate: '2027-01-20',
    manager: 'Lê Hoàng Minh',
    department: 'Phòng Quản lý Kỹ thuật',
    disbursement: 600000000,
    notes: 'Đo quan trắc lún chu kỳ 4 đảm bảo trong giới hạn thiết kế cho phép.',
    approvalDate: '2026-01-15',
    contractDate: '2026-01-18',
  },
  {
    id: 'GT-09/XL-2026',
    name: 'Hoàn thiện nội thất văn phòng làm việc và sảnh đón tiếp',
    type: 'Xây lắp',
    selectionMethod: 'Chào hàng cạnh tranh',
    budget: 12500000000,
    progress: 0,
    status: 'Đang thực hiện',
    startDate: '2026-09-01',
    endDate: '2026-12-25',
    manager: 'Nguyễn Thị Lan',
    department: 'Ban Quản lý Dự án số 1',
    disbursement: 0,
    notes: 'Đang trình duyệt hồ sơ mời thầu thiết kế nội thất chi tiết.',
    actualStatus: 'Chuẩn bị trình duyệt hồ sơ thiết kế chi tiết 3D.',
    lcntDuration: 25,
  },
  {
    id: 'GT-10/PT-2026',
    name: 'Dịch vụ vệ sinh công nghiệp và dọn dẹp tổng thể sau xây dựng',
    type: 'Phi tư vấn',
    selectionMethod: 'Chỉ định thầu rút gọn',
    budget: 850000000,
    progress: 0,
    status: 'Đang thực hiện',
    startDate: '2026-11-20',
    endDate: '2026-12-25',
    manager: 'Trần Hoài Nam',
    department: 'Phòng Hành chính - Quản trị',
    disbursement: 0,
    notes: 'Sẽ triển khai ký hợp đồng khi công trình hoàn thành 90% phần thô và hoàn thiện.',
    actualStatus: 'Chờ hoàn thiện cơ bản kết cấu thô để đàm phán.',
    lcntDuration: 15,
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-06-27T08:30:00Z',
    userEmail: 'nhokboytuananh@gmail.com',
    action: 'Cập nhật tiến độ',
    packageName: 'Thi công xây lắp khối nhà chính và hạ tầng kỹ thuật',
    details: 'Cập nhật tiến độ xây lắp khối nhà chính từ 70% lên 75%. Đang đổ bê tông sàn tầng 8.',
  },
  {
    id: 'log-2',
    timestamp: '2026-06-26T14:15:00Z',
    userEmail: 'nhokboytuananh@gmail.com',
    action: 'Cập nhật tiến độ',
    packageName: 'Cung cấp và lắp đặt hệ thống cơ điện (MEP) toàn khu',
    details: 'Cập nhật tiến độ MEP từ 35% lên 40%. Đã nhận hàng Chiller tại cảng Cát Lái.',
  },
  {
    id: 'log-3',
    timestamp: '2026-06-25T10:00:00Z',
    userEmail: 'pm.minh@company.com.vn',
    action: 'Thay đổi ghi chú',
    packageName: 'Thi công hệ thống đường nội bộ, thoát nước và cảnh quan',
    details: 'Bổ sung thông tin vướng mắc mặt bằng thoát nước chính gây chậm tiến độ 15 ngày.',
  },
  {
    id: 'log-4',
    timestamp: '2026-06-24T16:45:00Z',
    userEmail: 'director.long@company.com.vn',
    action: 'Duyệt hồ sơ thầu',
    packageName: 'Cung cấp hệ thống máy chủ và trang thiết bị CNTT trung tâm dữ liệu',
    details: 'Phê duyệt hồ sơ mời thầu và phát hành thông báo mời thầu rộng rãi.',
  }
];
